[programs.devnet]
solanacode = "BD2gFbWn1ocGaMAFBca67AhciQEsiQcX9otNv6vJo6vf"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/bensparks/.config/solana/id.json"

[scripts]
test = "node tests/solanacode.js" 
